// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0MecWTMEipQgU-HQdKQh30Rc6Pi75Koo',
    appId: '1:1081253610835:web:4366963172eba11a994da6',
    messagingSenderId: '1081253610835',
    projectId: 'journal-a2963',
    authDomain: 'journal-a2963.firebaseapp.com',
    storageBucket: 'journal-a2963.appspot.com',
    measurementId: 'G-79Z5S9EV18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2QwO0xPYgKNjk3FUqzq_zOPAFQ26ekfk',
    appId: '1:1081253610835:android:1263605b0cfe295a994da6',
    messagingSenderId: '1081253610835',
    projectId: 'journal-a2963',
    storageBucket: 'journal-a2963.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtOkYyLOmlInc6tkw6bIpSVp5nKjFAjTQ',
    appId: '1:1081253610835:ios:d01fb18d3a3c0a9f994da6',
    messagingSenderId: '1081253610835',
    projectId: 'journal-a2963',
    storageBucket: 'journal-a2963.appspot.com',
    iosBundleId: 'com.example.journal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtOkYyLOmlInc6tkw6bIpSVp5nKjFAjTQ',
    appId: '1:1081253610835:ios:d01fb18d3a3c0a9f994da6',
    messagingSenderId: '1081253610835',
    projectId: 'journal-a2963',
    storageBucket: 'journal-a2963.appspot.com',
    iosBundleId: 'com.example.journal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0MecWTMEipQgU-HQdKQh30Rc6Pi75Koo',
    appId: '1:1081253610835:web:a407eeeea65c1657994da6',
    messagingSenderId: '1081253610835',
    projectId: 'journal-a2963',
    authDomain: 'journal-a2963.firebaseapp.com',
    storageBucket: 'journal-a2963.appspot.com',
    measurementId: 'G-1S5F8LC7H9',
  );
}
